/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DscAppMenuService } from "../dscAppMenu.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DscAppMenuCreateInput } from "./DscAppMenuCreateInput";
import { DscAppMenu } from "./DscAppMenu";
import { DscAppMenuFindManyArgs } from "./DscAppMenuFindManyArgs";
import { DscAppMenuWhereUniqueInput } from "./DscAppMenuWhereUniqueInput";
import { DscAppMenuUpdateInput } from "./DscAppMenuUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DscAppMenuControllerBase {
  constructor(
    protected readonly service: DscAppMenuService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DscAppMenu })
  @swagger.ApiBody({
    type: DscAppMenuCreateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "DscAppMenu",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDscAppMenu(
    @common.Body() data: DscAppMenuCreateInput
  ): Promise<DscAppMenu> {
    return await this.service.createDscAppMenu({
      data: data,
      select: {
        createdAt: true,
        id: true,
        menuName: true,
        menuPath: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DscAppMenu] })
  @ApiNestedQuery(DscAppMenuFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DscAppMenu",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dscAppMenus(@common.Req() request: Request): Promise<DscAppMenu[]> {
    const args = plainToClass(DscAppMenuFindManyArgs, request.query);
    return this.service.dscAppMenus({
      ...args,
      select: {
        createdAt: true,
        id: true,
        menuName: true,
        menuPath: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DscAppMenu })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DscAppMenu",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dscAppMenu(
    @common.Param() params: DscAppMenuWhereUniqueInput
  ): Promise<DscAppMenu | null> {
    const result = await this.service.dscAppMenu({
      where: params,
      select: {
        createdAt: true,
        id: true,
        menuName: true,
        menuPath: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DscAppMenu })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: DscAppMenuUpdateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "DscAppMenu",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDscAppMenu(
    @common.Param() params: DscAppMenuWhereUniqueInput,
    @common.Body() data: DscAppMenuUpdateInput
  ): Promise<DscAppMenu | null> {
    try {
      return await this.service.updateDscAppMenu({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          menuName: true,
          menuPath: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DscAppMenu })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DscAppMenu",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDscAppMenu(
    @common.Param() params: DscAppMenuWhereUniqueInput
  ): Promise<DscAppMenu | null> {
    try {
      return await this.service.deleteDscAppMenu({
        where: params,
        select: {
          createdAt: true,
          id: true,
          menuName: true,
          menuPath: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
