/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, DscAppMenu as PrismaDscAppMenu } from "@prisma/client";

export class DscAppMenuServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DscAppMenuCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dscAppMenu.count(args);
  }

  async dscAppMenus(
    args: Prisma.DscAppMenuFindManyArgs
  ): Promise<PrismaDscAppMenu[]> {
    return this.prisma.dscAppMenu.findMany(args);
  }
  async dscAppMenu(
    args: Prisma.DscAppMenuFindUniqueArgs
  ): Promise<PrismaDscAppMenu | null> {
    return this.prisma.dscAppMenu.findUnique(args);
  }
  async createDscAppMenu(
    args: Prisma.DscAppMenuCreateArgs
  ): Promise<PrismaDscAppMenu> {
    return this.prisma.dscAppMenu.create(args);
  }
  async updateDscAppMenu(
    args: Prisma.DscAppMenuUpdateArgs
  ): Promise<PrismaDscAppMenu> {
    return this.prisma.dscAppMenu.update(args);
  }
  async deleteDscAppMenu(
    args: Prisma.DscAppMenuDeleteArgs
  ): Promise<PrismaDscAppMenu> {
    return this.prisma.dscAppMenu.delete(args);
  }
}
